# Create your models here.
from django.db import models

class UserID(models.Model):
    "user_id: generated by GET /userID"
    user_id = models.CharField(max_length=64)
    def __str__(self):
        return '{}'.format(self.user_id)


class Chat(models.Model):
    "user_id: 64-length string generated by /GET userID"
    user_id = models.CharField(max_length=64)
    "chat_type: question | answer"
    chat_type = models.CharField(max_length=10, auto_created=True, default="question")
    "content"
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{},{},{},{}'.format(self.user_id, self.chat_type, self.content, self.created_at)